version: "3.7"
services:
  db: 
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks: 
        default:
          aliases: 
            - database
    environment:
      MYSQL_ROOT_PASSWORD:  wes123
    volumes:
      - ./db/data:/var/lib/mysql
  api:
      build: ./
      container_name: django-container
      stop_signal: SIGINT
      networks: 
        default:
          aliases: 
            - api
      volumes:
        - ./mysite:/usr/src/app
      ports:
        - "8000:8000"
  web:
    image: nginx
    volumes:
      - ./templates/conf:/etc/nginx/conf.d/
      - ../front-end/enquete-webapp/dist/enquete-webapp:/var/www/angular
    networks: 
        default:
          aliases: 
            - web
    ports:
      - "8080:80"
      - "8181:81"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80